### ISSUE TITLE
Create a list and public depository of definitions to explain headers in all data

### ISSUE THREAD

**Issue by StuMackenzie** [MotusWTS/Motus-TO-DO#1]

**Comment by jbrzusto** [comment]
Maybe start with these:

   https://sensorgnome.org/Post-Processing_Telemetry_Data/Tag_Table_Columns

I haven't checked the format of the .csv files to see whether names in these are consistent
with the previous .rds files  Many users will have code that uses these, so we should try

maintain back-compatibility, either in the names, or by providing a function to convert them.

**Comment by pmorrill** [comment]
test comment

**Comment by cjardine-bsc** [comment]
There is this for downloaded data 
https://motus.org/data/downloads/api-proxy/fields

**Comment by pmorrill** [comment]
I have put a fix in the beta2 branch (it went into sandbox yesterday). There was a no-longer-necessary reset called on the response after the content type was set for csv files. Removing that eset should sort this out for good.

**Comment by Hussell** [comment]
Even knowing there was a link to this CSV somewhere on the site, it took me quite a while to find it.
https://motus.org/data/downloads

The current location is very easy to miss. I suggest putting the link in a more prominent location, for example between the instructions and the select-project widget or actually in the list of files which can be downloaded.

**Comment by pmorrill** [comment]
I see that the char encoding is still not working properly, though it tested fine within my dev environment last week. I'll take a look today.

**Comment by pmorrill** [comment]
Sorry - cancel that! My bad not setting the import encoding correctly in OpenOffice. I think that it now works ok.
