### ISSUE TITLE
Codeset drop-down not set to reflect database value on "Edit Tag" page

### ISSUE THREAD

**Issue by jbrzusto** [MotusWTS/Motus-TO-DO#10]
e.g.:
https://motus.org/data/tags/edit?projectID=57&id=23108

The codeSet field returned by the Motus API for this tag is **Lotek4**, which is correct,
but the drop down box just shows `--Select--`.

**Comment by Hussell** [comment]
Verified. This is a bug still present on beta and sandbox.

**Comment by pmorrill** [comment]
Looks like our lookup table for this field is keying on 'Lotek-4' instead of 'Lotek4'. I'll ask Catherine re the impact of a change to that lookup table.

**Comment by Hussell** [comment]
The codeset column in the tags table isn't constrained to be a foreign key from the lk_tag_codesets table. Since this is caused by a problem in the database, I'm reassigning to Catherine.

**Comment by Hussell** [comment]
The original example is fixed, but others remain, e.g. https://motus.org/data/tags/edit?projectID=132&id=23239

**Comment by cjardine-bsc** [comment]
Database changes complete. Close issue.
