### ISSUE TITLE
Pagination broken due to missing JS function

### ISSUE THREAD

**Issue by Hussell** [MotusWTS/Motus-TO-DO#13]
Clicking the "View all records in one page" link when managing tags or receivers on sandbox currently causes a JavaScript error: "ReferenceError: checkForRedirect is not defined". Working correctly on beta.

E.g.: https://sandbox.motus.org/data/project/tags?projectID=128

**Comment by pmorrill** [comment]
I picked this up too - and fixed it early this week. Should test ok now.
