### ISSUE TITLE
Manage Data link broken when project selected

### ISSUE THREAD

**Issue by StuMackenzie** [MotusWTS/Motus-TO-DO#16]
When a project has been selected from "Manage Data" - the page Manage Data/Manage Project returns a 404
 
Presumably reselecting this page should take you to either the main Select a Project Page, or Project Management Page.

**Comment by Hussell** [comment]
Fixed on beta and sandbox. Awaiting upload to the live site.

**Comment by denislepage** [comment]
Beta2 published
