### ISSUE TITLE
validate user API returns project names with escaped forward slashes

### ISSUE THREAD

**Issue by jbrzusto** [MotusWTS/Motus-TO-DO#18]
The API is:

   https://motus.org/api/user/validate

and although otherwise working, the return value is escaping
forward slashes (i.e. prefixing them with a `\` character),
e.g.:

```
..., "156":"Black Tern movements - breeding\/migration", ...

                                          ^^^^
                                      should just be 'breeding/migration'
```

This is not done by the motusListProjects API, for example, so is not
how the project name is actually stored at motus.  It's a picky
detail, but it might be symptomatic of something that leads to a future
more serious issue with other characters in project names.

**Comment by pmorrill** [comment]
John: could you check for these escapes in the 'motusListProjects' again? I checked the entry point that I think you might be referring to, and it too is presenting escaped forward slashes.

Send me the specific url that you are hitting if you do not see escaped slashes. (I may be testing the wrong api point).

**Comment by jbrzusto** [comment]
Just realized I've been using v1.0 for this one, where the problem doesn't appear:

   https://motus.org/data/api/v1.0/listprojects.jsp

**Comment by jbrzusto** [comment]
Just realized the user validate API has the same problem:

```
curl --data-urlencode json="{\"login\":\"john\",\"pword\":\"XXX\",\"date\":\"20170619145100\"}" https://motus.org/api/user/validate
```
returns, in part,


```
..., "39":"Nol\/Parada- Blackpoll Warbler Migration", ...
```

**Comment by pmorrill** [comment]
This problem seems to be coming from our json handler library. I've done some reading and it is hard-coded into the library (for the dubious reason that it allows the result to be displayed within javascript tags on the client). We have to either switch libraries, or perform a brute-force regex 'replace' after serialization, to get rid of the escape slashes. I am going to try the latter to start with.

**Comment by pmorrill** [comment]
For the record, this Mozilla spec page describes how to escape in Javascript:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types?redirectlocale=en-US&redirectslug=JavaScript%2FGuide%2FValues%2C_variables%2C_and_literals#String_literals

and includes the following line:
-----------
For characters not listed in the table, a preceding backslash is ignored, but this usage is deprecated and should be avoided.
-----------

Table is shown just above this instruction. So the client-side json parser should ignore this problematic backslash (a forward slash is not in the table). But, why it is being added in the first place is a bit obscure. I will experiment with scrubbing it out.

**Comment by pmorrill** [comment]
I have added a brute-force scrub of the escapes on forward slashes - in sandbox (master branch) only.

**Comment by pmorrill** [comment]
Fix went into beta2 today: next build of beta and deploy to live should remove these spurious escapes.
