### ISSUE TITLE
Landowner page issues

### ISSUE THREAD

**Issue by zcrysler** [MotusWTS/Motus-TO-DO#22]
When you try to delete a landowner by clicking on the garbage can icon, it just brings you to that landowner's page and doesn't delete

Also looks like you should be able to click on the deployments listed with each landowner but you can't - it would be useful if the links brought you to the receiver deployment page

**Comment by Hussell** [comment]
The landowners page has been undergoing a major redesign for the next release (see, e.g. https://sandbox.motus.org/data/project/landowners?projectID=1 ). I'm assigning this to Paul, and he can close it as soon as he's satisfied that these issues will be addressed in the next release.

**Comment by pmorrill** [comment]
The beta server now supports the new landowner / site management; Zoe is testing deployment record creation / save functions.
