### ISSUE TITLE
bugs in dropdown menu

### ISSUE THREAD

**Issue by zcrysler** [MotusWTS/Motus-TO-DO#23]
Once you select a project here: https://motus.org/data If you click on manage project it tries to take you to: https://motus.org/data/project/?id=78 instead of https://motus.org/data?projectID=107

Manage Users is working correctly. Manage tags and manage receivers takes you back to https://motus.org/data

Any idea what has been changed that's causing these redirects to fail? This is happening on the live site, so should be a priority. 

And from Paul:

If I start here: https://motus.org/data?projectID=157 and use the dropdown for 'Manage Project', I land here: https://motus.org/data/project/?id=157 (this is a 404 error - not a functioning script at all: it should be https://motus.org/data/project/edit?id=157)

Also: if you start here: https://motus.org/data/project/edit?id=157 and use the dropdowns, they seem to work. So they work in general, but the landing page is not setting the correct session variable for the projectId, I'd guess.

**Comment by Hussell** [comment]
This is the same as #16, which has been fixed in beta and sandbox, but is awaiting Denis' return to be uploaded to the live server.

**Comment by jbrzusto** [comment]
Okay, thanks - I'll work around it for now.

On Tue, Jun 13, 2017, at 11:31, Jeremy Hussell wrote:
> This is the same as #16, which has been fixed in beta and sandbox, but is awaiting Denis' return to be uploaded to the live server.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/MotusWTS/Motus-TO-DO/issues/23#issuecomment-308135536


-- 
#-----------------------------------
#  John Brzustowski
#  Wolfville, NS  Canada
