### ISSUE TITLE
user/validate API returning JSON strings in non-UTF-8 encoding

### ISSUE THREAD

**Issue by jbrzusto** [MotusWTS/Motus-TO-DO#25]
This is breaking pages that use motus.org for user validation, such as

   https://sensorgnome.org/upload

### Example ###
Calling this API:
```
https://motus.org/api/user/validate
```
with query parameter `json` equal to:
```JSON
{
   "login": "john",
   "pword": "XXX",
   "date": "20170613114800"
}
```
returns a JSON string with this fragment:
```JSON
"160":"Myotis movements in eastern Qu�bec",
```
where the placeholder character is of course supposed to be é

Note that the project information editable by the motus user here:

   https://motus.org/data/project/edit?id=160

is correctly given in UTF-8.

**Comment by Hussell** [comment]
The result looks like it's encoded correctly, to me, but the response header contains:
Content-Type: application/json;charset=ISO-8859-1

**Comment by jbrzusto** [comment]
which looks like this problem:

https://stackoverflow.com/questions/34521880/stop-tomcat-from-enforcing-iso-8859-1

On Tue, Jun 13, 2017, at 16:49, Jeremy Hussell wrote:
> The result looks like it's encoded correctly, to me, but the response header contains:
> Content-Type: application/json;charset=ISO-8859-1
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/MotusWTS/Motus-TO-DO/issues/25#issuecomment-308228187


-- 
#-----------------------------------
#  John Brzustowski
#  Wolfville, NS  Canada

**Comment by Hussell** [comment]
The header is fixed on all servers now. John, would you test to confirm that the header was causing the original problem?

**Comment by jbrzusto** [comment]
it's returning correct UTF-8 now on the production server.
