### ISSUE TITLE
User settings when PI creates a new project

### ISSUE THREAD

**Issue by zcrysler** [MotusWTS/Motus-TO-DO#27]
User permissions for PIs that create new projects seem to be automatically set to  "Read" for Project, and "None" for Tags, Receivers, and Data.  Eg. when logged in as Junior (user ID 234) for project "161 Migration connectivity of the Rusty Blackbird", you can't get to any of the metadata including users.

**Comment by Hussell** [comment]
Users who create a new project are now given full permissions (as they should have been). You can safely test this on sandbox, and the same fix is in place on beta, though not yet on the live site.

PIs who created a project in the past have not had their permissions updated yet. (A quick query shows 4 such.)
