### ISSUE TITLE
Receiver serial numbers

### ISSUE THREAD

**Issue by zcrysler** [MotusWTS/Motus-TO-DO#29]
I think we need to be more clear on the receiver registration page - since we need the serial numbers in a specific format we should explain better what that is.  For example, the instructions say "typically sometime like SG-1234BBBK5678, or Lotek-0123" which is usually fine, but Lotek 800's should be "Lotek-123".  Just had a user send a frustrated email about not being able to register an 800 after trying a number of different combos which always included the leading zeros' since the number on the unit is 000159.  I think we should spell it out to them what Lotek serial numbers should look like - and maybe when they enter it wrong, instead of just a standard error message "Data was not saved:
Receiver ID was not saved, as it does not match the expected pattern for this receiver type."
we explain what the options are.

**Comment by Hussell** [comment]
Lotek SRX 800: Lotek-XXX
Lotek SRX 600: Lotek-6XXX
Lotek SRX DL: Lotek-8XXX or Lotek-DXXXXXX
SensorGnome:
SG-XXXXBBBKXXXX
SG-XXXXBBBKXXXX_X
SG-XXXXBB0XXXXX
SG-XXXXBB0XXXXX_X
SG-XXXXRPIXXXXX
SG-XXXXRPIXXXXX_X

**Comment by Hussell** [comment]
I've edited the instructions on the sandbox (but not elsewhere, yet). Is that good enough to put into production?

https://sandbox.motus.org/data/receivers/edit?projectID=1
