### ISSUE TITLE
searchtags API versions 1.0 and 2.0 both failing

### ISSUE THREAD

**Issue by jbrzusto** [MotusWTS/Motus-TO-DO#3]
This API is used whenever the metadata cache on the processing server needs refreshing,
which is at most daily.

Today, the usual call failed:

```
2017-03-17 11:03:25 , get , http://motus.org/data/api/v1.0/searchtags.jsp ,
json =
{
   "serno":"SG-815BBBK1352",
   "hash":"73A8C38E1AB51FFFB2444E4BFB54AB8946582927",
   "date":"20170317110325",
   "format":"jsonp",
   "login":"john",
   "pword":"XXX",
   "projectID":null,
   "tsStart":null,
   "tsEnd":null,
   "searchMode":"startsBetween",
   "defaultLifespan":90,
   "lifespanBuffer":1.5,
   "regStart":null,
   "regEnd":null,
   "mfgID":null
}

==>

ERROR:  Error: Internal Server Error
```

and when I tried the v 2.0 API on the beta server with the same json
and this URL  https://beta.motus.org/api/tags/search

I got this problem:

```
Error in value[[3L]](cond) :
  MotusQuery failed with error; Error in parseJSON(txt): parse error: after key and value, inside map, I expect ',' or '}'
          atus":"pending","dtStart":2015-07-13 01:45:00 +00:00,"dtEnd"
                     (right here) ------^
```
where it appears the dtStart field is being returned as a formatted date/time,
rather than as the simple unix-style numeric timestamp that I need.
(The parseJOSN() error is due to the formatted date not being quoted.)

**Comment by denislepage** [comment]
The error on API 1.0 has been fixed. It related to invalid dates that managed to slip through for deployment dates. I'll let Paul address the issue with API 2.0

**Comment by jbrzusto** [comment]
fixed by motus.org
