### ISSUE TITLE
New species option

### ISSUE THREAD

**Issue by zcrysler** [MotusWTS/Motus-TO-DO#30]
Can we add "Columba livia domestica" as a species option - homing pigeon for Tara's project #

**Comment by Hussell** [comment]
Maybe use "Columba livia (Feral Pigeon)" as opposed to "Columba livia (Wild type)" until someone more knowledgeable gets back to you about this.

**Comment by cjardine-bsc** [comment]
Tara should use Columba livia (Feral)
