### ISSUE TITLE
new "list projects" API missing 'code' field

### ISSUE THREAD

**Issue by jbrzusto** [MotusWTS/Motus-TO-DO#32]
The original API:
```
https://motus.org/data/api/v1.0/listprojects.jsp
```
returns these fields:
```
id                 name    code  tagsPermissions sensorsPermissions
 0   Motus Test Project  NO_PROJ               0                  0
 1  Motus Ontario Array    Motus               2                  2
 2 Motus Atlantic Array MotusATL               2                  2
...
```
but its replacement API:
```
https://motus.org/api/projects
```
is missing the 'code' field (which is used e.g. to give tags human-readable names):
```
id                 name tagPermissions sensorPermissions
 0   Motus Test Project              0                 0
 1  Motus Ontario Array              2                 2
 2 Motus Atlantic Array              2                 2
...
```

**Comment by Hussell** [comment]
Huh. It looks like none of us knew what the project_code column was for, so it's missing from:
- the database views (i.e. vwBase_project_info and vwData_project_info)
- the API
- the user interface for editing projects

Also, the database has gotten out-of-date, with 37 projects having NULL for in the project_code column.

As a temporary workaround until this is fixed, taking the first 20 characters of the project name seems OK. About half of the current projects have names of 20 characters or less anyway, and it's a good backup plan when the project code is null.

**Comment by cjardine-bsc** [comment]
I'm not convinced that the project_code field is actually needed in the database on our end (though I'm happy to be contradicted). I'm going to hold off putting it in the views for now and can discuss during Thursday's call.

**Comment by pmorrill** [comment]
I  have adjusted the sandbox api call to include 'code' in the return package, for the simple project list John describes above. It is not part of the longer 'project descriptions' package though. This latter is based on vwData_project_info verbatim, so we can add the code in there to have it show up in the 'descriptions' package. If code is null, am using first 20 chars of project name.

**Comment by Hussell** [comment]
John, after discussing this a bit, we have a few questions:
- Where and when are project codes used?
- Are there any other ways they might be used in future?
- What form are they supposed to take (i.e. length, allowed characters, etc.)?
- Do project codes have to be unique?
- Could project codes be replaced by the project ID?

**Comment by jbrzusto** [comment]
They're for convenience in labelling items on graphs, and objects in datasets where we want
a short, human-readable label for a project.  They really should be unique.  Beyond that,
it's really up to users to decide.
So, e.g. for a plot showing all tags detected by a receiver during a season, people want to
see what other projects' tags were detected.

**Comment by cjardine-bsc** [comment]
I've populated the 37 project codes that were missing and altered the views to include project code.

**Comment by Hussell** [comment]
I've added UI for editing the project code to the sandbox, but I've had to disable validation there because the codes from the live database were not tested in motus_sandbox first, so the nulls are still present, and there's a bug in UserLandingPage (/data) which crashes if a project which is in an invalid state is selected.

So, when Catherine fixes the null codes in motus_sandbox, I'll turn on the project code validation again. Meanwhile, Paul should have a look at UserLandingPage, which calls ProjectBean.getProjectBean, which in turn redirects to the user landing page if there's an error. UserLandingPage then fails to check if an error occurred, tries to dispatch to a JSP, and fails due to the response already being committed.

**Comment by cjardine-bsc** [comment]
I updated sandbox so the project_code fields are fully populated.

**Comment by jbrzusto** [comment]
The sandbox version looks good.

On Mon, Jul 3, 2017, at 13:09, cjardine-bsc wrote:
> I updated sandbox so the project_code fields are fully populated. 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/MotusWTS/Motus-TO-DO/issues/32#issuecomment-312684889


-- 
#-----------------------------------
#  John Brzustowski
#  Wolfville, NS  Canada

**Comment by Hussell** [comment]
Projects created on the live site won't have valid project codes until after the next release. Errors are occurring in beta and sandbox when a project does not have a valid project code (and whenever a project fails validation despite our best efforts). On sandbox, project #98 (Zvenigorod) has been given an invalid project code for testing purposes (thanks Catherine!).

https://sandbox.motus.org/data?projectID=98
https://sandbox.motus.org/data/project/users?projectID=98
https://sandbox.motus.org/data/project/tags?projectID=98
https://sandbox.motus.org/data/project/recvs?projectID=98
https://sandbox.motus.org/data/project/sites?projectID=98
etc. (pretty much every page, including deployments)

The main culprit seems to be ProjectBean.getProjectBean. This method triggers a redirect and returns null when an error occurs, but just returns null if no project is selected.

**Comment by Hussell** [comment]
Fixes are deployed and tested.
