### ISSUE TITLE
Broken link in main menu: Exploration des données > Projects

### ISSUE THREAD

**Issue by Hussell** [MotusWTS/Motus-TO-DO#35]
E.g. on https://beta.motus.org/data/viewtracks.jsp?lang=fr, the link is https://beta.motus.org/data/projects/?lang=fr but should be https://beta.motus.org/data/projects?lang=fr

**Comment by cjardine-bsc** [comment]
I fixed it, but the menu links on Beta are not transferred over to live, so they don't need to be functioning correctly. They were made to test everything before the launch of beta 1 but will probably fall out of sync going forward, unless of course you need anything created for testing.

**Comment by Hussell** [comment]
Sandbox and Beta are where all our internal testing occurs. If they fall out of sync, bugs like this won't get caught until they hit the live site and real users report them. (Also, the testers will just keep reporting issues in the old versions whether or not they were fixed on the live site.) So if you're in need of something to do, setting up a way to test on sandbox and beta then deploy to live seems like it would prevent a lot of future pain.

P.S.: the link on beta.motus.org hasn't changed for me, and I don't see any new commits in the repository
