### ISSUE TITLE
Manage Data -> Manage Users

### ISSUE THREAD

**Issue by Hussell** [MotusWTS/Motus-TO-DO#36]
Two things: the link in the menu will need to be updated to point to /data/project/users, and that link will have to behave properly when the projectID parameter is missing (right now it throws a null pointer error).

https://sandbox.motus.org/data/project/users
https://beta.motus.org/data/project/users

**Comment by cjardine-bsc** [comment]
I've made the change to the WP menus, the .jsp pages will not be updated until the sites are re-deployed.

**Comment by pmorrill** [comment]
I've checked in the fix for the user mgmt servlet, so that you can set the dropdown menu item to point to

/data/project/users

(when the beta3 goes live, presumably)

**Comment by Hussell** [comment]
Deployed and tested. Looks like everything is working correctly.
