### ISSUE TITLE
tag registration API fails

### ISSUE THREAD

**Issue by jbrzusto** [MotusWTS/Motus-TO-DO#40]
e.g.

API:  https://motus.org/api/tag/register

request:

```
json={"serno":"SG-0815BBBK1352",
"hash":"6C4234A1B8391D7DE808AD366E67371D8D3F823B",
"date":"20170727152824",
"format":"jsonp",
"login":"john",
"pword":"XXX",
"projectID":95,
"mfgID":"515",
"manufacturer":"Lotek",
"model":"NTQB-1",
"type":"ID",
"codeSet":"Lotek4",
"offsetFreq":0.0,
"period":16.6939,
"periodSD":0.0014,
"pulseLen":2.5,
"param1":134.28,
"param2":97.66,
"param3":73.24,
"param4":0.0,
"param5":0.0,
"param6":0.0,
"paramType":1,
"ts":1501169299.2773,
"nomFreq":166.38,
"dateBin":"2017-3"}
```

is giving error:

```
Content-Length : "60"
Content-Type   : "application/json;charset=UTF-8"
Server         : "Microsoft-IIS/7.5"
X-Powered-By   : "ASP.NET"
Date           : "Thu, 27 Jul 2017 15:32:10 GMT"
status         : "400"
statusMessage  : "Bad Request\r\n"
```

The last successful tag registration was on July 21, and there have
been no relevant changes to the client-side code since then, as
far as I'm aware.  All tag registrations since then have failed.

**Comment by pmorrill** [comment]
John: can you try this same registration against the beta server (which is running of the live database). ie:

https://beta.motus.org/api/tag/register

**Comment by pmorrill** [comment]
John: the code expects format to be 
"fmt" : "jsonp"
But there should be a default of json assigned.

You are not seeing any motus error returned, right?

**Comment by pmorrill** [comment]
I am getting back a proper motus error when I submit this: to the live server:

{"version":"2.0","errorCode":"permission-denied","errorMsg":"Insufficient permissions - You are not authorized to manage tags on this project"} 

(since your password is not correct in the package.) Can you re-test ?

**Comment by jbrzusto** [comment]
With all combinations of 
   `https://beta.motus.org/api/tag/register` or `https://motus.org/api/tag/register`
and 
   `"format":"jsonp"` or `"fmt":"jsonp"`
I'm getting no json-formatted error, but instead, the same header-level error messages as
in the first post of this issue.

However, when I try resubmit the same package using command-line curl, it succeeds.

This is strange; I haven't modified anything on my end that should have changed the format
of queries.

**Comment by jbrzusto** [comment]
Weird - the only over-the-wire difference between the two ways of calling the API mentioned above are the
`Content-Encoding` header on the request.
- `application/json` doesn't work, despite having been in use since at least 13 June, 2017 and so present for ~ 400 successful tag registrations up until 20 July, 2017
- `application/x-www-form-urlencoded` **does** work

So I'll switch to the latter, as the former isn't correct, but it would be useful to know what changed to
break previous functionality...
