### ISSUE TITLE
receiver SG-1013BB000626 needs a deployment record for 2015

### ISSUE THREAD

**Issue by jbrzusto** [MotusWTS/Motus-TO-DO#42]
There are 600k tag detections from that receiver that year, but no receiver deployment record.
It was presumably deployed by project 8 or 110.
The dates according to data files are:

Wed Sep  9 18:42:00 GMT 2015  to   Mon Nov  2 10:31:47 GMT 2015

and the GPS location is:

```sql
select avg(lat), avg(lon) from gps where batchID=19;
+-------------------+--------------------+
| avg(lat)          | avg(lon)           |
+-------------------+--------------------+
| 43.73599563928766 | -69.79972116438356 |
+-------------------+--------------------+
```

The deployment record for a receiver is used to provide:
- receiver metadata for all detections to tag owners
- detections of "foreign" tags to receiver owner.

So without this deployment record:
- users whose tags were detected won't obtain *metadata* for this receiver
- the project which deployed this receiver won't obtain detections of other people's
  tags during that deployment.

**Comment by zcrysler** [comment]
Project 110 Holberton 2015-2016 has that receiver with a 2016 deployment in that location - I've contacted Rebecca and will update the deployment when I hear back

**Comment by zcrysler** [comment]
Deployment for 2015 has been entered - this issue can be closed
