### ISSUE TITLE
Switching to French (or to English)

### ISSUE THREAD

**Issue by Hussell** [MotusWTS/Motus-TO-DO#49]
Manage receivers or tags, then switch to French (or English). Some interface elements will still be in English (or French) until you switch to another project or otherwise cause the cached parts of the interface to change. In some cases, elements of the interface simply disappear.

Examples:

https://beta.motus.org/data/project/recvs?projectID=1 (tab names and table headers don't change)
https://beta.motus.org/data/project/tags?projectID=10 (same)

https://beta.motus.org/data/receivers/edit?projectID=1&id=383 (table headers don't change, status and type never change)
https://beta.motus.org/data/tags/edit?projectID=10&id=11326 (table headers don't change, status and marker type never change)

https://beta.motus.org/data/receiver/deployment/edit?projectID=1&id=681 (antennas tab disappears until you click the other tab and click back)
https://beta.motus.org/data/tag/deployment/edit?projectID=10&id=4911 (species and morphology tab disappears until you click the other tab and click back)

**Comment by pmorrill** [comment]
These issues should be resolved with new deployment.

**Comment by Hussell** [comment]
Tab names and table header names seem to be fixed.

French versions of deployment status and tower type can be retrieved from lk_deployment_status and lk_fixture_type respectively, but I haven't found a table containing marker types. (There probably isn't one, it isn't a foreign key and that field is full of typos.)

The first tab not appearing when editing a deployment in French seems to be a separate issue, due to a JavaScript syntax error.

**Comment by pmorrill** [comment]
The fixes yesterday should have sorted the javascript issue: the sandbox seems to be working; possible that the beta3 was not built after I committed those?

I added the mapping to fr for fixture type, and status in main deployments listing table this morning.
