### ISSUE TITLE
RTL2832U dongle support

### ISSUE THREAD

**Issue by rossjd** [MotusWTS/Motus-TO-DO#5]
The RTL2832U dongle with R820T2 tuner chip appears to be an option for Motus detections, but I'm unable to integrate it into the existing Sensorgnome build on my RPI2B. It seems that there should be a way to get the SG boot file to recognize the chip vendor (0bda) and product (2838) IDs, but there are a few layers too many layers for me to cut through.

Another possibility is to tune and filter the I/O stream from the dongle (see http://osmocom.org/projects/sdr/wiki/rtl-sdr or https://git.osmocom.org/rtl-sdr/) and then output this stream live (through a FIFO?) to the SG analysis.

I'm willing to do some groundwork, but I figured I'd ask here to see if this is an easy fix or needs some finessing of the rtl-sdr output.  Thanks for any advice you can provide.

Jeremy Ross

**Comment by jbrzusto** [comment]
It is an option, but not yet implemented.  I'm closing this issue in deference to:

   https://github.com/jbrzusto/sensorgnome/issues/13
