### ISSUE TITLE
Private project info in some views

### ISSUE THREAD

**Issue by Hussell** [MotusWTS/Motus-TO-DO#50]
Receiver deployments from private projects are being displayed on the receivers map because they appear in vwData_receivers_deployments with an access level of 0.

Attempting to view https://beta.motus.org/data/receiverDeployment?id=944 generates a null pointer error for the same reason. (The code finds the entry in vwData_receivers_deployments, then quite reasonably assumes that there must exist an entry in vwData_project_info for the given project ID.)

**Comment by cjardine-bsc** [comment]
vwData_receivers_deployments has been altered to exclude projects where is_private_project <> 1 

Same has been done for tag deployments.
