### ISSUE TITLE
Can't create new landowner

### ISSUE THREAD

**Issue by zcrysler** [MotusWTS/Motus-TO-DO#51]
Saving after creating a new landowner brings you to a HTTP Status 404 error page.  I get the same page when I click on "landowners" from the link within this: Manage data › Project "Motus Ontario Array" (#1) › Landowners › Edit.  The second error only happens when I'm on the new landowner page that won't save, it works fine when you're looking at an existing landowner.

However, it does appear to save the new landowner despite the error, and in this case it saved twice (I clicked save a few times).

**Comment by pmorrill** [comment]
I have posted a fix into beta3 and master branches. Zoe: It needs testing before we push it to live.

**Comment by zcrysler** [comment]
I tested on beta 3:
- When I enter a first name and a state, then click save, the page reverts to blank entries and when I go back to the landowner page it has not been saved
- when I enter a first name, a state and a last name, then click save, I still get the 404 page

**Comment by pmorrill** [comment]
We always need to check that Jeremy as re-deployed the code before testing these fixes. I'll try it again later today. I also think that the first situation might be something differernt: the code is probably requiring at least a surname OR an affiliation. Of course, it should report an error if one of these is not provided. I'll look at that today.

**Comment by Hussell** [comment]
I was away yesterday (moving into a new house), so didn't do a deployment. I've just finished deploying everything, so try testing now.

**Comment by pmorrill** [comment]
Zoe: we need to retest this now. t looks ok, but you should check it on the beta server. In summary: the save problems should be gone, and the 'province/state' field is no longer mandatory. The only restriction on the data record is that at least one of the following must be provided: surname OR company

**Comment by zcrysler** [comment]
Just tested - working fine and ready for a push to the live site
