### ISSUE TITLE
Short name required for project creation

### ISSUE THREAD

**Issue by zcrysler** [MotusWTS/Motus-TO-DO#59]
https://motus.org/data/project/edit?id=170 - I'm getting a warning that "you must provide a short name for the project"  - is this the shortlabel that will get used for tagIDs in the hourly plots and detection data files?  If so there should be an explanation on the project page so that users make a good short name.  

- what's the length limit?
- inform them that it will be seen by everyone (if it's what I'm thinking it is)
- hopefully there's some default to prevent duplicates in the very slim chance that two projects give themselves the same short name

**Comment by Hussell** [comment]
This is indeed the short name used in generating tag names.

* It's limited to 20 ASCII characters (i.e. no accents, emoticons, or other weird characters which might break some plotting tool out there).
* Everything on that page is going to be seen by everyone (see e.g. https://motus.org/data/project?id=170).
* Duplicates are currently allowed, and some already exist, so it isn't as unlikely as you might think. Duplicates so far are all pairs of projects run by the same person.

I think it makes sense to add a sentence or two describing what the short name is for. Maybe: "The short project name is used to label data on graphs and in other places where space is at a premium but a human-readable project name is still needed."

**Comment by Hussell** [comment]
I've added a help icon to the short project name on beta and sandbox.
https://beta.motus.org/data/project/edit?id=170
