### ISSUE TITLE
beta site:  tag deployment display swaps lat and long

### ISSUE THREAD

**Issue by jbrzusto** [MotusWTS/Motus-TO-DO#6]
e.g.:
   https://beta.motus.org/data/tags/edit?projectID=128&id=22927
This tag was deployed in Panama, and the tag deployment record obtained via
an API call has the **correct** lat/lon:
```sql
sqlite> select tagID, latitude, longitude from tagDeps where tagID=22927;
tagID       latitude    longitude 
----------  ----------  ----------
22927       8.95        -79.55    

```

**Comment by Hussell** [comment]
Verified, this is a bug still present on beta and sandbox.

**Comment by pmorrill** [comment]
Yes - column headings are actually switched. I have fixed it in the sandbox.

Do we need to push to live release or can we wait until next release version?

**Comment by Hussell** [comment]
This should be fixed on beta too, since it's an easily fixed bug.

Coordinates are almost universally given as latitude then longitude, so the columns should be shown in that order to reduce input errors.

**Comment by pmorrill** [comment]
Checked a fix into Beta2, and will do same for sandbox shortly (preserving the lat then long ordering in the header of this table and correcting the field values)
