### ISSUE TITLE
Scale on map

### ISSUE THREAD

**Issue by zcrysler** [MotusWTS/Motus-TO-DO#60]
A scale on the receivers map would be really useful for planning and visualizing the network

**Comment by Hussell** [comment]
I've turned on Google Maps' default scale indicator. It's at the bottom of the screen, between the imagery credits and the terms of use. The Google Maps API doesn't allow any configuration of the scale indicator beyond turning it on and off, so if you need anything more complicated it'll take a lot longer to make.

**Comment by zcrysler** [comment]
That's great, I don't think we need anything more complicated than that, I was looking for gaps in the network and just wanted to be able to see roughly how far apart stations were without having to do my own plot.
