### ISSUE TITLE
API: species is not restricting search appropriately

### ISSUE THREAD

**Issue by jbrzusto** [MotusWTS/Motus-TO-DO#62]
The `qlang` parameter for this call is supposed to restrict the search space for `qstr`,
with value `CD` meaning "only search short code".  At least that's how it used to work.

But this request:

2017-08-31 16:54:07 , get , https://motus.org/api/species , {"date":"20170831165407","fmt":"json","login":"john","pword":"XXX,"qstr":"SAND","nrec":null,"group":"BIRDS","qlang":"CD"}

is returning 61 species with "SAND" anywhere in their name:
```
    id                     english                       french
   260              Hawaiian Goose                Bernache néné
 31019              Sand Partridge               Perdrix de Hey
  1860             Hawaiian Petrel             Pétrel des Hawaï
  3840               Hawaiian Rail          Marouette des Hawaï
  4010              Sandhill Crane               Grue du Canada
  4120          Lesser Sand-Plover          Pluvier de Mongolie
...
```

which led to this problem:  jbrzusto/TO_DO#97

(luckily, most 4-letter codes don't match english or french names)

**Comment by pmorrill** [comment]
This should be fixed in the next beta build. We need to check it later today, then we'll want a push to live.

**Comment by pmorrill** [comment]
I spoke too soon - there is still some element that is not cooperating.

**Comment by Hussell** [comment]
Resolved in the latest deployment.
