### ISSUE TITLE
Tag download link broken

### ISSUE THREAD

**Issue by zcrysler** [MotusWTS/Motus-TO-DO#63]
The "download all tags" button from this page: https://motus.org/data/project/tags?projectID=14 gives you the warning:

This site can’t be reached

The webpage at https://motus.org/api/tags/template?json=%7B"date"%3A"20170905163226"%2C"isInternal"%3A545%2C"fmt"%3A"csv"%2C"projectID"%3A14%2C"internalHash"%3A"fc97d4d16f2261d6b5be310d7c02236c2bf60432ee2ba3cb269714ff4e4f079f9a0a82a48df3bb2a959548f573b6fdbe4eddb995e7b29540038b187917a71275"%7D might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

Get the same error on beta

**Comment by pmorrill** [comment]
I have checked in a fix: the api is working but the template construction failed to set a variable, causing a null pointer exception.

You should see it work again after the next build of beta3.

**Comment by Hussell** [comment]
Deployed. Seems to be working on beta and sandbox.
