### ISSUE TITLE
table on page "Tags Registered for this Project" should include tag period

### ISSUE THREAD

**Issue by jbrzusto** [MotusWTS/Motus-TO-DO#8]
For most users, a tag is identified by the combination of its manufacturer ID ("Tag Label") **and** period,
so these should both appear in that table, ideally next to each other.
e.g.

  https://beta.motus.org/data/project/tags?projectID=130

**Comment by Hussell** [comment]
The manufacturer ID and date bin together uniquely identify every tag in every project. On the other hand, there are examples of duplicate manufacturer ID + period in many projects. E.g. https://motus.org/data/tag?id=17500 and https://motus.org/data/tag?id=17539

**Comment by jbrzusto** [comment]
Sure, but users might forget which tag #123 they added the '.1' or
whatever suffix to in the manufacturer ID field, but might know what
the burst interval (period) is.  So it's helpful to include both,
even if it's redundant as far as which tag is being referred to, given
the dateBin. I realize the information is in the detailed view
for the tag, so this is a pretty small issue; I only reported it
because I found it a bit annoying when I was trying to verify
some registrations, that I had to go into the detailed record
to be sure which tag was being referred to by "123.1", for example.

Another example:  the person recording registrations for the tags has a
batch of tags with two tags labelled #123; all they know is that they
have different periods, and they've just put an ink dot on the label
of one of the tags to distinguish between them. The dot on the tag
makes that one "123.1", but they don't necessarily know what the
period is, so the interface should make that connection for them,
because later on, it might matter to whomever is deploying the
tag or entering metadata.  It would save them a bit of back
and forth between the list and detail views to have the period
visible in the former.

Anyway, that's my lobbying done; it's obviously up to you/motus.

J.

**Comment by Hussell** [comment]
Seems reasonable. That table is a little crowded though: are there any columns you wouldn't be bothered to see removed to make room for the period (e.g. Nom. Freq.)?

**Comment by jbrzusto** [comment]
Or perhaps combine Deployment Status and Deployed somehow?
Or remove manufacturer?

**Comment by zcrysler** [comment]
Manufacturer probably isn't as important - could also combine manufacturer and model.  It would definitely be useful to show the burst rate though, I've had the same frustrations as John trying to sort out tag issues for multiple projects

**Comment by Hussell** [comment]
Manufacturers in the database:
Lotek 11,495
NULL 3

So I agree that column is currently useless. About 90% of tags have a Nom. Freq of 166.38, and about 10% use 150. However, almost no projects use both. I think it's one frequency for Nor. Am. and one for Europe? So I'd recommend getting rid of that column too.

That frees up enough room to add the tag period. Clarification request: is "burst rate" the same thing as "period"?

**Comment by pmorrill** [comment]
For the moment, I have removed manufacturer and added period (visible in the sandbox on next build).
